### ISSUE TITLE
Utbedre dokumentasjon om hvordan man bør sette riktig tekst-stiler i en app

### ISSUE THREAD

**Issue by hakonph** [navikt/aksel#670]
fargen krever at du har wrappet hele appen i en .app

https://github.com/navikt/nav-frontend-moduler/blob/1c56ee215a238f147a1c3c2cbe1d24013b14ebc1/packages/node_modules/nav-frontend-typografi-style/src/index.less#L5-L10

**Comment by Lillebo** [comment]
Hm, tror de stilene der er mer ment å være til hjelp enn et krav 🤔 Du kan jo fortsatt sette de samme stilene på hvilket som helst element du selv ønsker:

```less
@import (reference) '~nav-frontend-core/less/_variabler';
@import '~nav-frontend-typografi-style/src/index';

.minDiv {
    color: @navMorkGra;
    font-family: @font-family;
}
```
